[package]
name = "aac_trim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mp4 = "0.12.0"
fdk-aac = "0.4.0"
